{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-12-21T02:23:04.814726Z",
     "iopub.status.busy": "2024-12-21T02:23:04.814279Z",
     "iopub.status.idle": "2024-12-21T02:23:12.374329Z",
     "shell.execute_reply": "2024-12-21T02:23:12.373435Z",
     "shell.execute_reply.started": "2024-12-21T02:23:04.814568Z"
    },
    "trusted": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.2 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 701, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\asyncio\\windows_events.py\", line 322, in run_forever\n",
      "    super().run_forever()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\asyncio\\base_events.py\", line 641, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\asyncio\\base_events.py\", line 1986, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 523, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 429, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 767, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 429, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\Sara\\AppData\\Local\\Temp\\ipykernel_29164\\4037520186.py\", line 6, in <module>\n",
      "    import pandas as pd\n",
      "  File \"C:\\Users\\Sara\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\__init__.py\", line 39, in <module>\n",
      "    from pandas.compat import (\n",
      "  File \"C:\\Users\\Sara\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\compat\\__init__.py\", line 27, in <module>\n",
      "    from pandas.compat.pyarrow import (\n",
      "  File \"C:\\Users\\Sara\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\compat\\pyarrow.py\", line 8, in <module>\n",
      "    import pyarrow as pa\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\pyarrow\\__init__.py\", line 65, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "ImportError",
     "evalue": "\nA module that was compiled using NumPy 1.x cannot be run in\nNumPy 2.0.2 as it may crash. To support both 1.x and 2.x\nversions of NumPy, modules must be compiled with NumPy 2.0.\nSome module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n\nIf you are a user of the module, the easiest solution will be to\ndowngrade to 'numpy<2' or try to upgrade the affected module.\nWe expect that some modules will need time to support NumPy 2.\n\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python312\\site-packages\\numpy\\core\\_multiarray_umath.py:44\u001b[0m, in \u001b[0;36m__getattr__\u001b[1;34m(attr_name)\u001b[0m\n\u001b[0;32m     39\u001b[0m     \u001b[38;5;66;03m# Also print the message (with traceback).  This is because old versions\u001b[39;00m\n\u001b[0;32m     40\u001b[0m     \u001b[38;5;66;03m# of NumPy unfortunately set up the import to replace (and hide) the\u001b[39;00m\n\u001b[0;32m     41\u001b[0m     \u001b[38;5;66;03m# error.  The traceback shouldn't be needed, but e.g. pytest plugins\u001b[39;00m\n\u001b[0;32m     42\u001b[0m     \u001b[38;5;66;03m# seem to swallow it and we should be failing anyway...\u001b[39;00m\n\u001b[0;32m     43\u001b[0m     sys\u001b[38;5;241m.\u001b[39mstderr\u001b[38;5;241m.\u001b[39mwrite(msg \u001b[38;5;241m+\u001b[39m tb_msg)\n\u001b[1;32m---> 44\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mImportError\u001b[39;00m(msg)\n\u001b[0;32m     46\u001b[0m ret \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mgetattr\u001b[39m(_multiarray_umath, attr_name, \u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[0;32m     47\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m ret \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[1;31mImportError\u001b[0m: \nA module that was compiled using NumPy 1.x cannot be run in\nNumPy 2.0.2 as it may crash. To support both 1.x and 2.x\nversions of NumPy, modules must be compiled with NumPy 2.0.\nSome module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n\nIf you are a user of the module, the easiest solution will be to\ndowngrade to 'numpy<2' or try to upgrade the affected module.\nWe expect that some modules will need time to support NumPy 2.\n\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.2 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 701, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\asyncio\\windows_events.py\", line 322, in run_forever\n",
      "    super().run_forever()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\asyncio\\base_events.py\", line 641, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\asyncio\\base_events.py\", line 1986, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 523, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 429, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 767, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 429, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\Sara\\AppData\\Local\\Temp\\ipykernel_29164\\4037520186.py\", line 6, in <module>\n",
      "    import pandas as pd\n",
      "  File \"C:\\Users\\Sara\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\__init__.py\", line 62, in <module>\n",
      "    from pandas.core.api import (\n",
      "  File \"C:\\Users\\Sara\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\core\\api.py\", line 9, in <module>\n",
      "    from pandas.core.dtypes.dtypes import (\n",
      "  File \"C:\\Users\\Sara\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\core\\dtypes\\dtypes.py\", line 24, in <module>\n",
      "    from pandas._libs import (\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\pyarrow\\__init__.py\", line 65, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "ImportError",
     "evalue": "\nA module that was compiled using NumPy 1.x cannot be run in\nNumPy 2.0.2 as it may crash. To support both 1.x and 2.x\nversions of NumPy, modules must be compiled with NumPy 2.0.\nSome module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n\nIf you are a user of the module, the easiest solution will be to\ndowngrade to 'numpy<2' or try to upgrade the affected module.\nWe expect that some modules will need time to support NumPy 2.\n\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python312\\site-packages\\numpy\\core\\_multiarray_umath.py:44\u001b[0m, in \u001b[0;36m__getattr__\u001b[1;34m(attr_name)\u001b[0m\n\u001b[0;32m     39\u001b[0m     \u001b[38;5;66;03m# Also print the message (with traceback).  This is because old versions\u001b[39;00m\n\u001b[0;32m     40\u001b[0m     \u001b[38;5;66;03m# of NumPy unfortunately set up the import to replace (and hide) the\u001b[39;00m\n\u001b[0;32m     41\u001b[0m     \u001b[38;5;66;03m# error.  The traceback shouldn't be needed, but e.g. pytest plugins\u001b[39;00m\n\u001b[0;32m     42\u001b[0m     \u001b[38;5;66;03m# seem to swallow it and we should be failing anyway...\u001b[39;00m\n\u001b[0;32m     43\u001b[0m     sys\u001b[38;5;241m.\u001b[39mstderr\u001b[38;5;241m.\u001b[39mwrite(msg \u001b[38;5;241m+\u001b[39m tb_msg)\n\u001b[1;32m---> 44\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mImportError\u001b[39;00m(msg)\n\u001b[0;32m     46\u001b[0m ret \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mgetattr\u001b[39m(_multiarray_umath, attr_name, \u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[0;32m     47\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m ret \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[1;31mImportError\u001b[0m: \nA module that was compiled using NumPy 1.x cannot be run in\nNumPy 2.0.2 as it may crash. To support both 1.x and 2.x\nversions of NumPy, modules must be compiled with NumPy 2.0.\nSome module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n\nIf you are a user of the module, the easiest solution will be to\ndowngrade to 'numpy<2' or try to upgrade the affected module.\nWe expect that some modules will need time to support NumPy 2.\n\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.2 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 701, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\asyncio\\windows_events.py\", line 322, in run_forever\n",
      "    super().run_forever()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\asyncio\\base_events.py\", line 641, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\asyncio\\base_events.py\", line 1986, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 523, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 429, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 767, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 429, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\Sara\\AppData\\Local\\Temp\\ipykernel_29164\\4037520186.py\", line 6, in <module>\n",
      "    import pandas as pd\n",
      "  File \"C:\\Users\\Sara\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\__init__.py\", line 62, in <module>\n",
      "    from pandas.core.api import (\n",
      "  File \"C:\\Users\\Sara\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\core\\api.py\", line 28, in <module>\n",
      "    from pandas.core.arrays import Categorical\n",
      "  File \"C:\\Users\\Sara\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\core\\arrays\\__init__.py\", line 1, in <module>\n",
      "    from pandas.core.arrays.arrow import ArrowExtensionArray\n",
      "  File \"C:\\Users\\Sara\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\core\\arrays\\arrow\\__init__.py\", line 5, in <module>\n",
      "    from pandas.core.arrays.arrow.array import ArrowExtensionArray\n",
      "  File \"C:\\Users\\Sara\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\core\\arrays\\arrow\\array.py\", line 50, in <module>\n",
      "    from pandas.core import (\n",
      "  File \"C:\\Users\\Sara\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\core\\ops\\__init__.py\", line 8, in <module>\n",
      "    from pandas.core.ops.array_ops import (\n",
      "  File \"C:\\Users\\Sara\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\core\\ops\\array_ops.py\", line 56, in <module>\n",
      "    from pandas.core.computation import expressions\n",
      "  File \"C:\\Users\\Sara\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\core\\computation\\expressions.py\", line 21, in <module>\n",
      "    from pandas.core.computation.check import NUMEXPR_INSTALLED\n",
      "  File \"C:\\Users\\Sara\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\core\\computation\\check.py\", line 5, in <module>\n",
      "    ne = import_optional_dependency(\"numexpr\", errors=\"warn\")\n",
      "  File \"C:\\Users\\Sara\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\compat\\_optional.py\", line 135, in import_optional_dependency\n",
      "    module = importlib.import_module(name)\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\numexpr\\__init__.py\", line 24, in <module>\n",
      "    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.2 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 701, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\asyncio\\windows_events.py\", line 322, in run_forever\n",
      "    super().run_forever()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\asyncio\\base_events.py\", line 641, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\asyncio\\base_events.py\", line 1986, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 523, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 429, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 767, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 429, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\Sara\\AppData\\Local\\Temp\\ipykernel_29164\\4037520186.py\", line 6, in <module>\n",
      "    import pandas as pd\n",
      "  File \"C:\\Users\\Sara\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\__init__.py\", line 62, in <module>\n",
      "    from pandas.core.api import (\n",
      "  File \"C:\\Users\\Sara\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\core\\api.py\", line 28, in <module>\n",
      "    from pandas.core.arrays import Categorical\n",
      "  File \"C:\\Users\\Sara\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\core\\arrays\\__init__.py\", line 1, in <module>\n",
      "    from pandas.core.arrays.arrow import ArrowExtensionArray\n",
      "  File \"C:\\Users\\Sara\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\core\\arrays\\arrow\\__init__.py\", line 5, in <module>\n",
      "    from pandas.core.arrays.arrow.array import ArrowExtensionArray\n",
      "  File \"C:\\Users\\Sara\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\core\\arrays\\arrow\\array.py\", line 64, in <module>\n",
      "    from pandas.core.arrays.masked import BaseMaskedArray\n",
      "  File \"C:\\Users\\Sara\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\core\\arrays\\masked.py\", line 60, in <module>\n",
      "    from pandas.core import (\n",
      "  File \"C:\\Users\\Sara\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\core\\nanops.py\", line 52, in <module>\n",
      "    bn = import_optional_dependency(\"bottleneck\", errors=\"warn\")\n",
      "  File \"C:\\Users\\Sara\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\compat\\_optional.py\", line 135, in import_optional_dependency\n",
      "    module = importlib.import_module(name)\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\site-packages\\bottleneck\\__init__.py\", line 7, in <module>\n",
      "    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,\n"
     ]
    },
    {
     "ename": "ImportError",
     "evalue": "\nA module that was compiled using NumPy 1.x cannot be run in\nNumPy 2.0.2 as it may crash. To support both 1.x and 2.x\nversions of NumPy, modules must be compiled with NumPy 2.0.\nSome module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n\nIf you are a user of the module, the easiest solution will be to\ndowngrade to 'numpy<2' or try to upgrade the affected module.\nWe expect that some modules will need time to support NumPy 2.\n\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python312\\site-packages\\numpy\\core\\_multiarray_umath.py:44\u001b[0m, in \u001b[0;36m__getattr__\u001b[1;34m(attr_name)\u001b[0m\n\u001b[0;32m     39\u001b[0m     \u001b[38;5;66;03m# Also print the message (with traceback).  This is because old versions\u001b[39;00m\n\u001b[0;32m     40\u001b[0m     \u001b[38;5;66;03m# of NumPy unfortunately set up the import to replace (and hide) the\u001b[39;00m\n\u001b[0;32m     41\u001b[0m     \u001b[38;5;66;03m# error.  The traceback shouldn't be needed, but e.g. pytest plugins\u001b[39;00m\n\u001b[0;32m     42\u001b[0m     \u001b[38;5;66;03m# seem to swallow it and we should be failing anyway...\u001b[39;00m\n\u001b[0;32m     43\u001b[0m     sys\u001b[38;5;241m.\u001b[39mstderr\u001b[38;5;241m.\u001b[39mwrite(msg \u001b[38;5;241m+\u001b[39m tb_msg)\n\u001b[1;32m---> 44\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mImportError\u001b[39;00m(msg)\n\u001b[0;32m     46\u001b[0m ret \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mgetattr\u001b[39m(_multiarray_umath, attr_name, \u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[0;32m     47\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m ret \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[1;31mImportError\u001b[0m: \nA module that was compiled using NumPy 1.x cannot be run in\nNumPy 2.0.2 as it may crash. To support both 1.x and 2.x\nversions of NumPy, modules must be compiled with NumPy 2.0.\nSome module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n\nIf you are a user of the module, the easiest solution will be to\ndowngrade to 'numpy<2' or try to upgrade the affected module.\nWe expect that some modules will need time to support NumPy 2.\n\n"
     ]
    }
   ],
   "source": [
    "# Install tensorflow package\n",
    "# %pip install --upgrade tensorflow\n",
    "\n",
    "\n",
    "import json\n",
    "import pandas as pd\n",
    "import re\n",
    "import numpy as np\n",
    "import string\n",
    "from tensorflow.keras.models import load_model \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "_cell_guid": "b1076dfc-b9ad-4769-8c92-a6c4dae69d19",
    "_uuid": "8f2839f25d086af736a60e9eeb907d3b93b6e0e5",
    "execution": {
     "iopub.execute_input": "2024-12-21T02:23:14.726839Z",
     "iopub.status.busy": "2024-12-21T02:23:14.726525Z",
     "iopub.status.idle": "2024-12-21T02:23:16.513000Z",
     "shell.execute_reply": "2024-12-21T02:23:16.512288Z",
     "shell.execute_reply.started": "2024-12-21T02:23:14.726813Z"
    },
    "trusted": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "480\n",
      "442\n"
     ]
    }
   ],
   "source": [
    "\n",
    "# model1\n",
    "model1 = load_model(r\"model1/model.keras\")\n",
    "# model2\n",
    "model2 = load_model(r\"model2/model.keras\")\n",
    "\n",
    "\n",
    "# load data of model1\n",
    "with open(r\"model1/tag2idx_model1.json\", \"r\") as file:\n",
    "    tag2idx1 = json.load(file)\n",
    "with open(r\"model1/word2idx_model1.json\", \"r\") as file:\n",
    "    word2idx1 = json.load(file)\n",
    "\n",
    "\n",
    "# load data of model2\n",
    "with open(r\"model2/tag2idx_model2.json\", \"r\") as file:\n",
    "    tag2idx2 = json.load(file)\n",
    "with open(r\"model2/word2idx_model2.json\", \"r\") as file:\n",
    "    word2idx2 = json.load(file)\n",
    "\n",
    "print(len(word2idx1))\n",
    "print(len(word2idx2))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-12-21T02:24:00.213377Z",
     "iopub.status.busy": "2024-12-21T02:24:00.213073Z",
     "iopub.status.idle": "2024-12-21T02:24:00.239321Z",
     "shell.execute_reply": "2024-12-21T02:24:00.238698Z",
     "shell.execute_reply.started": "2024-12-21T02:24:00.213352Z"
    },
    "trusted": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<>:2: SyntaxWarning: invalid escape sequence '\\P'\n",
      "<>:2: SyntaxWarning: invalid escape sequence '\\P'\n",
      "C:\\Users\\Sara\\AppData\\Local\\Temp\\ipykernel_29164\\386633851.py:2: SyntaxWarning: invalid escape sequence '\\P'\n",
      "  dev_data = pd.read_json(\"dataset\\PIZZA_dev.json\", lines=True)\n"
     ]
    }
   ],
   "source": [
    "# load dev data\n",
    "dev_data = pd.read_json(\"dataset\\PIZZA_dev.json\", lines=True)\n",
    "src_dev=dev_data[\"dev.SRC\"].to_numpy()\n",
    "top_dev=dev_data[\"dev.TOP\"]\n",
    "MAX_LEN=52\n",
    "words = word2idx1.keys()\n",
    "with open(\"top_dev.txt\", \"w\") as file:\n",
    "    for top in top_dev:\n",
    "        file.write(top + \"\\n\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-12-21T02:24:03.235714Z",
     "iopub.status.busy": "2024-12-21T02:24:03.235423Z",
     "iopub.status.idle": "2024-12-21T02:24:03.240071Z",
     "shell.execute_reply": "2024-12-21T02:24:03.239152Z",
     "shell.execute_reply.started": "2024-12-21T02:24:03.235693Z"
    },
    "trusted": true
   },
   "outputs": [],
   "source": [
    "idx2word1 = {v: k for k, v in word2idx1.items()}  \n",
    "idx2word2 = {v: k for k, v in word2idx2.items()}  \n",
    "idx2tag = {v: k for k, v in tag2idx1.items()}  \n",
    "idx2tag2 = {v: k for k, v in tag2idx2.items()}  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-12-21T02:24:05.774543Z",
     "iopub.status.busy": "2024-12-21T02:24:05.774211Z",
     "iopub.status.idle": "2024-12-21T02:24:05.787199Z",
     "shell.execute_reply": "2024-12-21T02:24:05.786505Z",
     "shell.execute_reply.started": "2024-12-21T02:24:05.774516Z"
    },
    "trusted": true
   },
   "outputs": [],
   "source": [
    "def convert_to_json(new_predicted1, new_predicted2, model1_words, unk):\n",
    "    # Helper variables\n",
    "    current_group = None\n",
    "    current_entity = {}\n",
    "    all_toppings = []\n",
    "    all_styles = []\n",
    "    json_result = {\"ORDER\": {\"PIZZAORDER\": [], \"DRINKORDER\": []}}\n",
    "    \n",
    "    try:\n",
    "        # Iterate through labels and words\n",
    "        for i, (entity_label, group_label) in enumerate(zip(new_predicted1, new_predicted2)):\n",
    "            word = model1_words[i]\n",
    "            if word == \"<UNK>\":\n",
    "                word = unk.pop(0)\n",
    "            \n",
    "            if group_label.startswith(\"B-\"):\n",
    "                # Save the previous group entity if it exists\n",
    "                if current_group == \"PIZZAORDER\" :\n",
    "                    if all_toppings:\n",
    "                        current_entity[\"ALLTOPPING\"] = all_toppings\n",
    "                        all_toppings = []\n",
    "                    if all_styles:\n",
    "                        current_entity[\"STYLE\"] = all_styles\n",
    "                        all_styles = []\n",
    "                    json_result[\"ORDER\"][\"PIZZAORDER\"].append(current_entity)\n",
    "                elif current_group == \"DRINKORDER\" and current_entity:\n",
    "                    json_result[\"ORDER\"][\"DRINKORDER\"].append(current_entity)\n",
    "                \n",
    "                # Start a new entity\n",
    "                current_group = group_label[2:]\n",
    "                current_entity = {}\n",
    "        \n",
    "            if entity_label == \"B-NUMBER\" and  current_entity.get(\"NUMBER\") is None:\n",
    "                current_entity[\"NUMBER\"] = word\n",
    "            elif entity_label == \"B-SIZE\":\n",
    "                current_entity[\"SIZE\"] = word\n",
    "            \n",
    "            elif entity_label in (\"B-STYLE\"):\n",
    "                all_styles.append({\"NOT\": False, \"TYPE\": word})\n",
    "            elif entity_label in (\"I-STYLE\"):\n",
    "                all_styles[-1][\"TYPE\"] += \" \" + word\n",
    "            elif entity_label in (\"B-NOT-STYLE\"):\n",
    "                all_styles.append({\"NOT\": True, \"TYPE\": word})\n",
    "            elif entity_label in (\"I-NOT-STYLE\"):\n",
    "                all_styles[-1][\"TYPE\"] += \" \" + word\n",
    "    \n",
    "            elif entity_label == \"B-QUANTITY\":\n",
    "                all_toppings.append({\"NOT\": False, \"QUANTITY\": word, \"TOPPING\": None})\n",
    "            elif entity_label == \"I-QUANTITY\":\n",
    "                all_toppings[-1][\"QUANTITY\"] += \" \" + word\n",
    "            elif entity_label == \"B-TOPPING\" and all_toppings and all_toppings[-1][\"TOPPING\"] is None:\n",
    "                all_toppings[-1][\"TOPPING\"] = word\n",
    "            elif entity_label == \"B-TOPPING\":\n",
    "                all_toppings.append({\"NOT\": False, \"QUANTITY\": None, \"TOPPING\": word})\n",
    "            elif entity_label == \"I-TOPPING\":\n",
    "                all_toppings[-1][\"TOPPING\"] += \" \" + word\n",
    "            elif entity_label == \"B-NOT-TOPPING\" and all_toppings and all_toppings[-1][\"TOPPING\"] is None:\n",
    "                all_toppings[-1][\"NOT\"] = True\n",
    "                all_toppings[-1][\"TOPPING\"] = word\n",
    "            elif entity_label == \"B-NOT-TOPPING\":\n",
    "                all_toppings.append({\"NOT\": True, \"QUANTITY\": None, \"TOPPING\": word})\n",
    "            elif entity_label == \"I-NOT-TOPPING\":\n",
    "                all_toppings[-1][\"TOPPING\"] += \" \" + word\n",
    "            elif entity_label == \"B-CONTAINERTYPE\":\n",
    "                current_entity[\"CONTAINERTYPE\"] = word\n",
    "            elif entity_label in (\"B-DRINKTYPE\", \"I-DRINKTYPE\"):\n",
    "                current_entity[\"DRINKTYPE\"] = current_entity.get(\"DRINKTYPE\", \"\") + \" \" + word\n",
    "        \n",
    "        # Add the last group entity\n",
    "        if current_group == \"PIZZAORDER\" :\n",
    "            if all_toppings:\n",
    "                current_entity[\"ALLTOPPING\"] = all_toppings\n",
    "            if all_styles:\n",
    "                current_entity[\"STYLE\"] = all_styles\n",
    "            json_result[\"ORDER\"][\"PIZZAORDER\"].append(current_entity)\n",
    "        elif current_group == \"DRINKORDER\" and current_entity:\n",
    "            json_result[\"ORDER\"][\"DRINKORDER\"].append(current_entity)\n",
    "    \n",
    "        # Remove empty orders\n",
    "        if 'PIZZAORDER' in json_result['ORDER'] and not json_result['ORDER']['PIZZAORDER']:\n",
    "            del json_result['ORDER']['PIZZAORDER']\n",
    "        if 'DRINKORDER' in json_result['ORDER'] and not json_result['ORDER']['DRINKORDER']:\n",
    "            del json_result['ORDER']['DRINKORDER']\n",
    "\n",
    "    \n",
    "    except Exception as e:\n",
    "        return {}\n",
    "    \n",
    "    return json_result\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-12-21T02:24:10.355989Z",
     "iopub.status.busy": "2024-12-21T02:24:10.355707Z",
     "iopub.status.idle": "2024-12-21T02:24:10.360367Z",
     "shell.execute_reply": "2024-12-21T02:24:10.359399Z",
     "shell.execute_reply.started": "2024-12-21T02:24:10.355966Z"
    },
    "trusted": true
   },
   "outputs": [],
   "source": [
    "def clean_alltopping(json_data):\n",
    "    for pizza in json_data.get(\"ORDER\", {}).get(\"PIZZAORDER\", []):\n",
    "        if \"ALLTOPPING\" in pizza:\n",
    "            # Filter out elements with a QUANTITY but no TOPPING\n",
    "            pizza[\"ALLTOPPING\"] = [\n",
    "                topping for topping in pizza[\"ALLTOPPING\"]\n",
    "                if not (topping.get(\"QUANTITY\") and not topping.get(\"TOPPING\"))\n",
    "            ]\n",
    "    return json_data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-12-21T02:27:01.747464Z",
     "iopub.status.busy": "2024-12-21T02:27:01.747094Z",
     "iopub.status.idle": "2024-12-21T02:27:01.758695Z",
     "shell.execute_reply": "2024-12-21T02:27:01.757943Z",
     "shell.execute_reply.started": "2024-12-21T02:27:01.747436Z"
    },
    "trusted": true
   },
   "outputs": [],
   "source": [
    "def predict(test_src):\n",
    "   \n",
    "    \n",
    "    for src in test_src:\n",
    "        allowed_punctuation = \"-_'\"\n",
    "        translation_table = src.maketrans('', '', string.punctuation.replace(allowed_punctuation, ''))\n",
    "        src=src.translate(translation_table)\n",
    "        unk=[]\n",
    "        src_words_orginal = src.split() \n",
    "        if(len(src_words_orginal)>MAX_LEN):\n",
    "            continue\n",
    "        # replace unknown words\n",
    "        for word in src_words_orginal:\n",
    "            if word not in words:\n",
    "                str=f\"(?:(?<=\\\\s)|^){word}(?:(?=\\\\s)|$)\"\n",
    "                src=re.sub(str,\"<UNK>\",src,flags=re.MULTILINE,count=1)\n",
    "                unk.append(word)\n",
    "        src_words=src.split()\n",
    "        # get the words indecies\n",
    "        src_indecies = [word2idx1.get(w) for w in src_words]\n",
    "        # pad\n",
    "        pad_token = word2idx1.get(\"<pad>\")  \n",
    "        src_indecies = src_indecies + [pad_token] * (MAX_LEN - len(src_words))\n",
    "        src_indecies = np.expand_dims(src_indecies, axis=0)  \n",
    "        # prediction\n",
    "        p = model1.predict(src_indecies)  \n",
    "        p = np.argmax(p, axis=-1)  # Get the predicted tag indices\n",
    "        \n",
    "        predicted1=[]\n",
    "        \n",
    "        for i,tag_idx in enumerate(p[0]):\n",
    "            tag_begin=idx2tag[tag_idx]\n",
    "            if tag_begin[0:2]==\"I-\" and i>0 and  tag_begin[2:-1]!=predicted1[-1][2:-1] :\n",
    "                tag_begin=re.sub(\"I-\",\"B-\",tag_begin)\n",
    "             \n",
    "            predicted1.append(tag_begin) \n",
    "\n",
    "\n",
    "        \n",
    "        ##################################################\n",
    "        \n",
    "        new_src_indecies=[]\n",
    "        for w,t in zip(src_indecies[0],predicted1):\n",
    "            if t !=\"O\":\n",
    "                new_src_indecies.append(w)\n",
    "\n",
    "        model1_words=[]\n",
    "        for w in new_src_indecies:\n",
    "            model1_words.append(idx2word1[w])\n",
    "\n",
    "    \n",
    "        model2_src_indecies=[]\n",
    "        for w in model1_words:\n",
    "            model2_src_indecies.append(word2idx2.get(w,word2idx2[\"<UNK>\"]))\n",
    "\n",
    "       \n",
    "        ###################################################\n",
    "        pad_token=word2idx2.get(\"<pad>\")  \n",
    "        model2_src_indecies = model2_src_indecies + [pad_token] * (MAX_LEN - len(model2_src_indecies))\n",
    "        model2_src_indecies = np.expand_dims(model2_src_indecies, axis=0)  # Shape: (1, 25)\n",
    "        p = model2.predict(model2_src_indecies)  \n",
    "        p = np.argmax(p, axis=-1)  # Get the predicted tag indices\n",
    "        predicted2=[]\n",
    "        for i,w in enumerate(p[0]):  # p is likely a batch, so take the first sequence\n",
    "            tag_begin=idx2tag2[w]\n",
    "            if tag_begin[0:2]==\"I-\" and i>0 and tag_begin[2:-1]!=predicted2[-1][2:-1] :\n",
    "                tag_begin=re.sub(\"I-\",\"B-\",tag_begin)\n",
    "            if tag_begin==\"B-QUANTITY\"  and i>0 and predicted2[-1]== \"I-QUANTITY\":\n",
    "                tag_begin=re.sub(\"B-\",\"I-\",tag_begin)\n",
    "            predicted2.append(tag_begin) \n",
    "\n",
    "        \n",
    "        new_predicted1=[]\n",
    "        new_predicted2=[]\n",
    "        for p1 in predicted1:\n",
    "            if p1!=\"O\":\n",
    "                 new_predicted1.append(p1)\n",
    "        for p2 in predicted2:\n",
    "            if p2!=\"O\":\n",
    "                 new_predicted2.append(p2)\n",
    "                \n",
    "        # conver to json\n",
    "        json_result=convert_to_json(new_predicted1,new_predicted2,model1_words,unk)\n",
    "        json_result=clean_alltopping(json_result)\n",
    "        print(json.dumps(json_result, indent=4))\n",
    "        \n",
    "\n",
    "\n",
    "        \n",
    "       \n",
    "        \n",
    "                \n",
    "                "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-12-21T02:28:01.428764Z",
     "iopub.status.busy": "2024-12-21T02:28:01.428423Z",
     "iopub.status.idle": "2024-12-21T02:28:01.581467Z",
     "shell.execute_reply": "2024-12-21T02:28:01.580711Z",
     "shell.execute_reply.started": "2024-12-21T02:28:01.428737Z"
    },
    "trusted": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[1m1/1\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 49ms/step\n",
      "\u001b[1m1/1\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 34ms/step\n",
      "{\n",
      "    \"ORDER\": {\n",
      "        \"PIZZAORDER\": [\n",
      "            {\n",
      "                \"NUMBER\": \"two\",\n",
      "                \"SIZE\": \"medium\",\n",
      "                \"ALLTOPPING\": [\n",
      "                    {\n",
      "                        \"NOT\": false,\n",
      "                        \"QUANTITY\": null,\n",
      "                        \"TOPPING\": \"sausage\"\n",
      "                    },\n",
      "                    {\n",
      "                        \"NOT\": false,\n",
      "                        \"QUANTITY\": null,\n",
      "                        \"TOPPING\": \"black olives\"\n",
      "                    }\n",
      "                ]\n",
      "            },\n",
      "            {\n",
      "                \"NUMBER\": \"two\",\n",
      "                \"SIZE\": \"medium\",\n",
      "                \"ALLTOPPING\": [\n",
      "                    {\n",
      "                        \"NOT\": false,\n",
      "                        \"QUANTITY\": null,\n",
      "                        \"TOPPING\": \"pepperoni\"\n",
      "                    },\n",
      "                    {\n",
      "                        \"NOT\": false,\n",
      "                        \"QUANTITY\": \"extra\",\n",
      "                        \"TOPPING\": \"cheese\"\n",
      "                    }\n",
      "                ]\n",
      "            },\n",
      "            {\n",
      "                \"NUMBER\": \"three\",\n",
      "                \"SIZE\": \"large\",\n",
      "                \"ALLTOPPING\": [\n",
      "                    {\n",
      "                        \"NOT\": false,\n",
      "                        \"QUANTITY\": null,\n",
      "                        \"TOPPING\": \"pepperoni\"\n",
      "                    },\n",
      "                    {\n",
      "                        \"NOT\": false,\n",
      "                        \"QUANTITY\": null,\n",
      "                        \"TOPPING\": \"sausage\"\n",
      "                    }\n",
      "                ]\n",
      "            }\n",
      "        ],\n",
      "        \"DRINKORDER\": [\n",
      "            {\n",
      "                \"NUMBER\": \"two\",\n",
      "                \"DRINKTYPE\": \" pepsi\"\n",
      "            }\n",
      "        ]\n",
      "    }\n",
      "}\n"
     ]
    }
   ],
   "source": [
    "\n",
    "\n",
    " predict([\"i want to order two medium pizzas with sausage and black olives and two medium pizzas with pepperoni and extra cheese and three large pizzas with pepperoni and sausage and two pepsi\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "trusted": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kaggle": {
   "accelerator": "gpu",
   "dataSources": [
    {
     "datasetId": 6346272,
     "sourceId": 10259012,
     "sourceType": "datasetVersion"
    },
    {
     "datasetId": 6235330,
     "sourceId": 10107840,
     "sourceType": "datasetVersion"
    },
    {
     "isSourceIdPinned": true,
     "modelId": 197388,
     "modelInstanceId": 175025,
     "sourceId": 205243,
     "sourceType": "modelInstanceVersion"
    },
    {
     "isSourceIdPinned": true,
     "modelId": 197389,
     "modelInstanceId": 175026,
     "sourceId": 205244,
     "sourceType": "modelInstanceVersion"
    }
   ],
   "dockerImageVersionId": 30823,
   "isGpuEnabled": true,
   "isInternetEnabled": true,
   "language": "python",
   "sourceType": "notebook"
  },
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
